const images = {
  logo: require("../images/authImg.png"),
  previous: require("../images/Arrow 1.png"),
  loginProfile: require("../images/profile-img.png"),
  mainLogo: require("../images/logo.png"),
  asideLogo: require("../images/asideLogo.png"),
  navIcon1: require("../images/noun-painter.png"),
  navIcon2: require("../images/noun-engineering.png"),
  navIcon3: require("../images/noun-front-desk.png"),
  user: require("../images/profile.png"),
  navIcon4: require("../images/dashboard.png"),
  navIcon5: require("../images/alarm.png"),
  navIcon6: require("../images/guest.png"),
  navIcon7: require("../images/Document.png"),
  navIcon8: require("../images/report.png"),
  navIcon9: require("../images/task.png"),
  navIcon10: require("../images/Danger Circle.png"),
  navIcon11: require("../images/noun-chat-781944 1.png"),
  navIcon12: require("../images/setting.png"),
  navIcon13: require("../images/to-do-list.png"),
  navIcon14: require("../images/employe.png"),
  navIcon15: require("../images/rooms.png"),
  navIcon16: require("../images/noun-machinery-maintenance-7066134 1.png"),
  user1: require("../images/1user.png"),
  user2: require("../images/3 User.png"),
  add: require("../images/add.png"),
  task2: require("../images/task (2).png"),
  edit : require("../images/edit.png"),
  delete: require("../images/Delete.png"),
  searchIcon: require("../images/search.png"),
  download: require ("../images/Vector (75).png"),
  eventrecurring: require ("../images/fluent-mdl2_recurring-event (1).png"),
  edit2: require ("../images/edit2.png"),
  cameraIcon: require("../images/camera.png"),
  profile: require("../images/profile (2).png"),
  qr: require("../images/qr.png"),
  issue1: require("../images/Rectangle 22715.png"),
  issue2: require("../images/Rectangle 22716.png"),
  issue3: require("../images/Rectangle 22717.png"),
  issue4: require("../images/Rectangle 22718.png"),
  issue5: require("../images/Rectangle 22719.png"),
  dangerIcon: require("../images/Danger.png"),
  groupChat1: require("../images/groupChat1.png"),
  groupChat2: require("../images/groupChat2.png"),
  groupChat3: require("../images/groupChat3.png"),
  chat1: require("../images/chat1.png"),
  chat2: require("../images/chat2.png"),
  chat3: require("../images/chat3.png"),
  chat4: require("../images/chat4.png"),
  send: require("../images/Frame (30).png"),
  emoji: require("../images/Layer_1.png"),
  del: require("../images/trashbin.png"),
  success: require("../images/check.png"),
  key: require("../images/noun-security-5269732 1.png"),
  updated: require("../images/update.png"),
  room: require("../images/room (2).png"),
  cancel: require("../images/remove.png"),
  data: require("../images/data.png"),
  delIcon: require("../images/trash.png"),
  editIcon: require("../images/editicon.png"),




};

export default images;
